package rocket.tfpoo;

/**
 *
 * @author yasmin
 */
public class JFrame extends javax.swing.JFrame {
    private GaragemCarros gc;
    private Patio patio;

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        LabelNomeSistema = new javax.swing.JLabel();
        iconRocket = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCriarTrem = new javax.swing.JMenu();
        menuListarTrens = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuInserirLocomotiva = new javax.swing.JMenuItem();
        menuInserirVagao = new javax.swing.JMenuItem();
        menuRemoverUltimoCarro = new javax.swing.JMenuItem();
        menuLocomotivasDisponíveis = new javax.swing.JMenuItem();
        menuVagoesDisponíveis = new javax.swing.JMenuItem();
        menuDesfazerTrem = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 215, 204));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        LabelNomeSistema.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        LabelNomeSistema.setForeground(new java.awt.Color(255, 255, 249));
        LabelNomeSistema.setText("Sisteminha de Trens!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(91, 191, 0, 178);
        jPanel1.add(LabelNomeSistema, gridBagConstraints);

        iconRocket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/equiperocket3x2.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 245, 75, 0);
        jPanel1.add(iconRocket, gridBagConstraints);

        menuCriarTrem.setText("Criar Trem");
        menuCriarTrem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCriarTremMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCriarTrem);

        menuListarTrens.setText("Listar Trens");
        menuListarTrens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuListarTrensMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuListarTrens);

        jMenu3.setText("Editar Trem");

        menuInserirLocomotiva.setText("Inserir Locomotiva");
        menuInserirLocomotiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInserirLocomotivaActionPerformed(evt);
            }
        });
        jMenu3.add(menuInserirLocomotiva);

        menuInserirVagao.setText("Inserir Vagão");
        menuInserirVagao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInserirVagaoActionPerformed(evt);
            }
        });
        jMenu3.add(menuInserirVagao);

        menuRemoverUltimoCarro.setText("Remover Último Carro");
        menuRemoverUltimoCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRemoverUltimoCarroActionPerformed(evt);
            }
        });
        jMenu3.add(menuRemoverUltimoCarro);

        menuLocomotivasDisponíveis.setText("Locomotivas Disponíveis");
        menuLocomotivasDisponíveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLocomotivasDisponíveisActionPerformed(evt);
            }
        });
        jMenu3.add(menuLocomotivasDisponíveis);

        menuVagoesDisponíveis.setText("Vagões Disponíveis");
        menuVagoesDisponíveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVagoesDisponíveisActionPerformed(evt);
            }
        });
        jMenu3.add(menuVagoesDisponíveis);

        jMenuBar1.add(jMenu3);

        menuDesfazerTrem.setText("Desfazer Trem");
        menuDesfazerTrem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDesfazerTremMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuDesfazerTrem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuInserirVagaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInserirVagaoActionPerformed
        JFrameInserirVagao jfVagao = new JFrameInserirVagao();
        jfVagao.infoCollector(gc,patio);
        jfVagao.setVisible(true);
    }//GEN-LAST:event_menuInserirVagaoActionPerformed

    private void menuInserirLocomotivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInserirLocomotivaActionPerformed
        JFrameInserirLocomotiva jfLoco = new JFrameInserirLocomotiva();
        jfLoco.infoCollector(gc,patio);
        jfLoco.setVisible(true);
    }//GEN-LAST:event_menuInserirLocomotivaActionPerformed

    private void menuRemoverUltimoCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRemoverUltimoCarroActionPerformed
        JFrameRemoveUltimo jfUltimo = new JFrameRemoveUltimo();
        jfUltimo.infoCollector(gc,patio);
        jfUltimo.setVisible(true);
    }//GEN-LAST:event_menuRemoverUltimoCarroActionPerformed

    private void menuLocomotivasDisponíveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLocomotivasDisponíveisActionPerformed
        JFrameListarLocomotivas jfLoco = new JFrameListarLocomotivas();
        jfLoco .infoCollector(gc,patio);
        jfLoco .setVisible(true);
    }//GEN-LAST:event_menuLocomotivasDisponíveisActionPerformed

    private void menuVagoesDisponíveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVagoesDisponíveisActionPerformed
        JFrameListarVagoes jfVagoes = new JFrameListarVagoes();
        jfVagoes .infoCollector(gc,patio);
        jfVagoes .setVisible(true);
    }//GEN-LAST:event_menuVagoesDisponíveisActionPerformed

    private void menuCriarTremMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCriarTremMouseClicked
        JFrameCriarTrem criarTrem = new JFrameCriarTrem();
        criarTrem.setVisible(true);
        criarTrem.infoCollector(gc, patio);
    }//GEN-LAST:event_menuCriarTremMouseClicked

    private void menuListarTrensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuListarTrensMouseClicked
        JFrameListarTrens listarTrens = new JFrameListarTrens();
        listarTrens.setVisible(true);
        listarTrens.infoCollector(gc, patio);
    }//GEN-LAST:event_menuListarTrensMouseClicked

    private void menuDesfazerTremMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDesfazerTremMouseClicked
        JFrameDesfazerTrem desfazTrem = new JFrameDesfazerTrem();
        desfazTrem.setVisible(true);
        desfazTrem.infoCollector(gc, patio);
    }//GEN-LAST:event_menuDesfazerTremMouseClicked
    
    public void infoCollector(GaragemCarros gc, Patio patio){
        this.gc = gc;
        this.patio = patio;
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelNomeSistema;
    private javax.swing.JLabel iconRocket;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenu menuCriarTrem;
    private javax.swing.JMenu menuDesfazerTrem;
    private javax.swing.JMenuItem menuInserirLocomotiva;
    private javax.swing.JMenuItem menuInserirVagao;
    private javax.swing.JMenu menuListarTrens;
    private javax.swing.JMenuItem menuLocomotivasDisponíveis;
    private javax.swing.JMenuItem menuRemoverUltimoCarro;
    private javax.swing.JMenuItem menuVagoesDisponíveis;
    // End of variables declaration//GEN-END:variables
}
