/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rocket.tfpoo;

/**
 *
 * @author yasmi
 */
public class JFrame extends javax.swing.JFrame {
    private GaragemCarros gc;
    private Patio patio;

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelNomeSistema = new javax.swing.JLabel();
        ButonDesfazer = new javax.swing.JButton();
        ButtonEditar = new javax.swing.JButton();
        ButtonListar = new javax.swing.JButton();
        ButtonCriar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCriarTrem = new javax.swing.JMenuItem();
        menuListarTrens = new javax.swing.JMenuItem();
        menuEditarTrem = new javax.swing.JMenuItem();
        menuDesfazerTrem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 215, 204));

        LabelNomeSistema.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        LabelNomeSistema.setForeground(new java.awt.Color(255, 255, 249));
        LabelNomeSistema.setText("Sistema de gerenciamento de trens");

        ButonDesfazer.setBackground(new java.awt.Color(255, 153, 153));
        ButonDesfazer.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        ButonDesfazer.setForeground(new java.awt.Color(255, 255, 249));
        ButonDesfazer.setText("Desfazer trem");
        ButonDesfazer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ButonDesfazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonDesfazerActionPerformed(evt);
            }
        });

        ButtonEditar.setBackground(new java.awt.Color(255, 153, 153));
        ButtonEditar.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        ButtonEditar.setForeground(new java.awt.Color(255, 255, 249));
        ButtonEditar.setText("Editar trem");
        ButtonEditar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarActionPerformed(evt);
            }
        });

        ButtonListar.setBackground(new java.awt.Color(255, 153, 153));
        ButtonListar.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        ButtonListar.setForeground(new java.awt.Color(255, 255, 249));
        ButtonListar.setText("Listar trens");
        ButtonListar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListarActionPerformed(evt);
            }
        });

        ButtonCriar.setBackground(new java.awt.Color(255, 153, 153));
        ButtonCriar.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        ButtonCriar.setForeground(new java.awt.Color(255, 255, 249));
        ButtonCriar.setText("Criar Trem");
        ButtonCriar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ButtonCriar.setDefaultCapable(false);
        ButtonCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCriarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonListar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButonDesfazer, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(LabelNomeSistema)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(LabelNomeSistema)
                .addGap(67, 67, 67)
                .addComponent(ButtonCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonListar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButonDesfazer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        menuCriarTrem.setText("Criar trem");
        menuCriarTrem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCriarTremActionPerformed(evt);
            }
        });
        jMenu1.add(menuCriarTrem);

        menuListarTrens.setText("Listar trens");
        menuListarTrens.setToolTipText("Lista os trens cadastrados no sistema");
        menuListarTrens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarTrensActionPerformed(evt);
            }
        });
        jMenu1.add(menuListarTrens);

        menuEditarTrem.setText("Editar trem");
        menuEditarTrem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarTremActionPerformed(evt);
            }
        });
        jMenu1.add(menuEditarTrem);

        menuDesfazerTrem.setText("Desfazer trem");
        menuDesfazerTrem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDesfazerTremActionPerformed(evt);
            }
        });
        jMenu1.add(menuDesfazerTrem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButonDesfazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonDesfazerActionPerformed
        JFrameDesfazerTrem desfaz = new JFrameDesfazerTrem();
        desfaz.setVisible(true);
        desfaz.infoCollector(gc, patio);
    }//GEN-LAST:event_ButonDesfazerActionPerformed

    private void ButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarActionPerformed
        JFrameEditarTrem criarTrem = new JFrameEditarTrem();
        criarTrem.setVisible(true);
        criarTrem.infoCollector(gc, patio);
    }//GEN-LAST:event_ButtonEditarActionPerformed

    private void ButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListarActionPerformed
        JFrameListarTrens listar = new JFrameListarTrens();
        listar.setVisible(true);
        listar.infoCollector(gc, patio);
    }//GEN-LAST:event_ButtonListarActionPerformed

    private void ButtonCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCriarActionPerformed

    }//GEN-LAST:event_ButtonCriarActionPerformed

    private void menuCriarTremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCriarTremActionPerformed
        
    }//GEN-LAST:event_menuCriarTremActionPerformed

    private void menuListarTrensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarTrensActionPerformed
        JFrameListarTrens listar = new JFrameListarTrens();
        listar.setVisible(true);
        listar.infoCollector(gc, patio);
    }//GEN-LAST:event_menuListarTrensActionPerformed

    private void menuEditarTremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarTremActionPerformed
        JFrameEditarTrem criarTrem = new JFrameEditarTrem();
        criarTrem.setVisible(true);
        criarTrem.infoCollector(gc, patio);
    }//GEN-LAST:event_menuEditarTremActionPerformed

    private void menuDesfazerTremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDesfazerTremActionPerformed
        JFrameDesfazerTrem desfaz = new JFrameDesfazerTrem();
        desfaz.setVisible(true);
        desfaz.infoCollector(gc, patio);
    }//GEN-LAST:event_menuDesfazerTremActionPerformed
    
    public void infoCollector(GaragemCarros gc, Patio patio){
        this.gc = gc;
        this.patio = patio;
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButonDesfazer;
    private javax.swing.JButton ButtonCriar;
    private javax.swing.JButton ButtonEditar;
    private javax.swing.JButton ButtonListar;
    private javax.swing.JLabel LabelNomeSistema;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuCriarTrem;
    private javax.swing.JMenuItem menuDesfazerTrem;
    private javax.swing.JMenuItem menuEditarTrem;
    private javax.swing.JMenuItem menuListarTrens;
    // End of variables declaration//GEN-END:variables
}
