/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rocket.tfpoo;

/**
 *
 * @author yasmi
 */
public class JFrameInserirLocomotiva extends javax.swing.JFrame {
    private GaragemCarros gc;
    private Patio patio;
    /**
     * Creates new form JFrameInserirLocomotiva
     */
    public JFrameInserirLocomotiva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboTrem = new javax.swing.JComboBox<>();
        comboLocomotiva = new javax.swing.JComboBox<>();
        buttonAdicionarLocomotiva = new javax.swing.JButton();
        labelLocomotiva = new javax.swing.JLabel();
        labelTrem = new javax.swing.JLabel();
        labelInsert = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 215, 204));

        comboTrem.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N

        comboLocomotiva.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        comboLocomotiva.setToolTipText("");

        buttonAdicionarLocomotiva.setBackground(new java.awt.Color(255, 153, 153));
        buttonAdicionarLocomotiva.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        buttonAdicionarLocomotiva.setForeground(new java.awt.Color(255, 255, 249));
        buttonAdicionarLocomotiva.setText("Adicionar");
        buttonAdicionarLocomotiva.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonAdicionarLocomotiva.setDefaultCapable(false);
        buttonAdicionarLocomotiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarLocomotivaActionPerformed(evt);
            }
        });

        labelLocomotiva.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        labelLocomotiva.setForeground(new java.awt.Color(255, 255, 249));
        labelLocomotiva.setText("Escolha uma locomotiva:");

        labelTrem.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        labelTrem.setForeground(new java.awt.Color(255, 255, 249));
        labelTrem.setText("Escolha um trem:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(labelInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(buttonAdicionarLocomotiva, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(153, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLocomotiva, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTrem, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboTrem, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboLocomotiva, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(labelInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTrem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTrem))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboLocomotiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLocomotiva))
                .addGap(18, 18, 18)
                .addComponent(buttonAdicionarLocomotiva, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAdicionarLocomotivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarLocomotivaActionPerformed
        String selected = comboLocomotiva.getSelectedItem().toString();
        String id = selected.substring(12, selected.length());
        int idLocomotiva = Integer.parseInt(id);
        selected = comboTrem.getSelectedItem().toString();
        id = selected.substring(6, selected.length());
        int idTrem = Integer.parseInt(id);
        Locomotiva locoadd = (Locomotiva) gc.getCarro(idLocomotiva);
        Trem tremadd = patio.getTrem(idTrem);
        boolean engatado = tremadd.engataLocomotiva(locoadd,gc);
        if(engatado){
            labelInsert.setText("Locomotiva inserida com sucesso");
        }
        int index = comboLocomotiva.getSelectedIndex();
        comboLocomotiva.removeItemAt(index);
    }//GEN-LAST:event_buttonAdicionarLocomotivaActionPerformed
    public void infoCollector(GaragemCarros gc, Patio patio){
        this.gc = gc;
        this.patio = patio;
        for(Carro c:gc.garagemCarro){
            if(c instanceof Locomotiva){
                String item = "Locomotiva: "+c.id;
                comboLocomotiva.addItem(item);
            }
        }
        for(Trem t:patio.trens){
            if(t.getQuantVagoes() == 0){
                String item = "Trem: "+t.getId();
                comboTrem.addItem(item);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionarLocomotiva;
    private javax.swing.JComboBox<String> comboLocomotiva;
    private javax.swing.JComboBox<String> comboTrem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelInsert;
    private javax.swing.JLabel labelLocomotiva;
    private javax.swing.JLabel labelTrem;
    // End of variables declaration//GEN-END:variables
}
