/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rocket.tfpoo;

/**
 *
 * @author yasmi
 */
public class JFrameRemoveUltimo extends javax.swing.JFrame {
    private GaragemCarros gc;
    private Patio patio;
    /**
     * Creates new form JFrameRemoveUltimo
     */
    public JFrameRemoveUltimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboTrem = new javax.swing.JComboBox<>();
        removerUltimo = new javax.swing.JButton();
        labelTrem = new javax.swing.JLabel();
        labelInsert = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 215, 204));

        comboTrem.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N

        removerUltimo.setBackground(new java.awt.Color(255, 153, 153));
        removerUltimo.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        removerUltimo.setForeground(new java.awt.Color(255, 255, 249));
        removerUltimo.setText("Remover ultimo carro");
        removerUltimo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        removerUltimo.setDefaultCapable(false);
        removerUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerUltimoActionPerformed(evt);
            }
        });

        labelTrem.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        labelTrem.setForeground(new java.awt.Color(255, 255, 249));
        labelTrem.setText("Escolha um trem");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(labelInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(removerUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(labelTrem)
                        .addGap(36, 36, 36)
                        .addComponent(comboTrem, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(labelInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTrem)
                    .addComponent(comboTrem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113)
                .addComponent(removerUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removerUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerUltimoActionPerformed
        String selected = comboTrem.getSelectedItem().toString();
        String id = selected.substring(6, selected.length());
        int idTrem = Integer.parseInt(id);
        Trem tremadd = patio.getTrem(idTrem);
        if(tremadd.getCarroByPos(tremadd.getSize()-1) instanceof Locomotiva){
            tremadd.desengataLocomotiva(gc);
        }else{
            tremadd.desengataVagao(gc); 
        }
        if(tremadd.getSize()==1){
            int index = comboTrem.getSelectedIndex();
            comboTrem.removeItemAt(index);
        }
        labelInsert.setText("Carro retirado com sucesso");
    }//GEN-LAST:event_removerUltimoActionPerformed

    public void infoCollector(GaragemCarros gc, Patio patio){
        this.gc = gc;
        this.patio = patio;
        for(Trem t:patio.trens){
            if(t.getSize()>1){
             String item = "Trem: "+t.getId();
             comboTrem.addItem(item);   
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboTrem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelInsert;
    private javax.swing.JLabel labelTrem;
    private javax.swing.JButton removerUltimo;
    // End of variables declaration//GEN-END:variables
}
