/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rocket.tfpoo;

/**
 *
 * @author yasmi
 */
public class JFrameRemoveUltimo extends javax.swing.JFrame {
    private GaragemCarros gc;
    private Patio patio;
    /**
     * Creates new form JFrameRemoveUltimo
     */
    public JFrameRemoveUltimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        comboTrem = new javax.swing.JComboBox<>();
        removerUltimo = new javax.swing.JButton();
        labelTrem = new javax.swing.JLabel();
        labelInsert = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 215, 204));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        comboTrem.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 178;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 18, 0, 142);
        jPanel1.add(comboTrem, gridBagConstraints);

        removerUltimo.setBackground(new java.awt.Color(255, 153, 153));
        removerUltimo.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        removerUltimo.setForeground(new java.awt.Color(255, 255, 249));
        removerUltimo.setText("Remover ");
        removerUltimo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        removerUltimo.setDefaultCapable(false);
        removerUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerUltimoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(65, 281, 151, 0);
        jPanel1.add(removerUltimo, gridBagConstraints);

        labelTrem.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        labelTrem.setForeground(new java.awt.Color(255, 255, 249));
        labelTrem.setText("Escolha um trem:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 115, 0, 0);
        jPanel1.add(labelTrem, gridBagConstraints);

        labelInsert.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelInsert.setForeground(new java.awt.Color(255, 153, 153));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 388;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(123, 192, 0, 142);
        jPanel1.add(labelInsert, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removerUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerUltimoActionPerformed
        String selected = comboTrem.getSelectedItem().toString();
        String id = selected.substring(6, selected.length());
        int idTrem = Integer.parseInt(id);
        Trem tremadd = patio.getTrem(idTrem);
        if(tremadd.getCarroByPos(tremadd.getSize()-1) instanceof Locomotiva){
            tremadd.desengataLocomotiva(gc);
        }else{
            tremadd.desengataVagao(gc); 
        }
        if(tremadd.getSize()==1){
            int index = comboTrem.getSelectedIndex();
            comboTrem.removeItemAt(index);
        }
        labelInsert.setText("Último elemento removido com sucesso!");
    }//GEN-LAST:event_removerUltimoActionPerformed

    public void infoCollector(GaragemCarros gc, Patio patio){
        this.gc = gc;
        this.patio = patio;
        for(Trem t:patio.trens){
            if(t.getSize()>1){
             String item = "Trem: "+t.getId();
             comboTrem.addItem(item);   
            }
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboTrem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelInsert;
    private javax.swing.JLabel labelTrem;
    private javax.swing.JButton removerUltimo;
    // End of variables declaration//GEN-END:variables
}
