package rocket.tfpoo;

/**
 *
 * @author yasmin
 */
public class JFrameEditarTrem extends javax.swing.JFrame {
    private GaragemCarros gc;
    private Patio patio;
    /**
     * Creates new form NewJFrame
     */
    public JFrameEditarTrem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        buttonOptionInserirLocomotiva = new javax.swing.JButton();
        buttonOptionRemoverCarro = new javax.swing.JButton();
        buttonOptionInserirVagao = new javax.swing.JButton();
        buttonOptionListarLocomotivas = new javax.swing.JButton();
        buttonOptionListarVagoes = new javax.swing.JButton();
        labelMenuEdicao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 215, 204));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        buttonOptionInserirLocomotiva.setBackground(new java.awt.Color(255, 153, 153));
        buttonOptionInserirLocomotiva.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        buttonOptionInserirLocomotiva.setForeground(new java.awt.Color(255, 255, 249));
        buttonOptionInserirLocomotiva.setText("Inserir Locomotiva");
        buttonOptionInserirLocomotiva.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonOptionInserirLocomotiva.setDefaultCapable(false);
        buttonOptionInserirLocomotiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOptionInserirLocomotivaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 156;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 151, 0, 152);
        jPanel1.add(buttonOptionInserirLocomotiva, gridBagConstraints);

        buttonOptionRemoverCarro.setBackground(new java.awt.Color(255, 153, 153));
        buttonOptionRemoverCarro.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        buttonOptionRemoverCarro.setForeground(new java.awt.Color(255, 255, 249));
        buttonOptionRemoverCarro.setText("Remover ÚItimo Carro");
        buttonOptionRemoverCarro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonOptionRemoverCarro.setDefaultCapable(false);
        buttonOptionRemoverCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOptionRemoverCarroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 113;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 151, 0, 152);
        jPanel1.add(buttonOptionRemoverCarro, gridBagConstraints);

        buttonOptionInserirVagao.setBackground(new java.awt.Color(255, 153, 153));
        buttonOptionInserirVagao.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        buttonOptionInserirVagao.setForeground(new java.awt.Color(255, 255, 249));
        buttonOptionInserirVagao.setText("Inserir Vagão");
        buttonOptionInserirVagao.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonOptionInserirVagao.setDefaultCapable(false);
        buttonOptionInserirVagao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOptionInserirVagaoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 217;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 151, 0, 152);
        jPanel1.add(buttonOptionInserirVagao, gridBagConstraints);

        buttonOptionListarLocomotivas.setBackground(new java.awt.Color(255, 153, 153));
        buttonOptionListarLocomotivas.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        buttonOptionListarLocomotivas.setForeground(new java.awt.Color(255, 255, 249));
        buttonOptionListarLocomotivas.setText("Listar Locomotivas Disponíveis");
        buttonOptionListarLocomotivas.setToolTipText("");
        buttonOptionListarLocomotivas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonOptionListarLocomotivas.setDefaultCapable(false);
        buttonOptionListarLocomotivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOptionListarLocomotivasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 151, 65, 152);
        jPanel1.add(buttonOptionListarLocomotivas, gridBagConstraints);

        buttonOptionListarVagoes.setBackground(new java.awt.Color(255, 153, 153));
        buttonOptionListarVagoes.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        buttonOptionListarVagoes.setForeground(new java.awt.Color(255, 255, 249));
        buttonOptionListarVagoes.setText("Listar Vagões Disponíveis");
        buttonOptionListarVagoes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonOptionListarVagoes.setDefaultCapable(false);
        buttonOptionListarVagoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOptionListarVagoesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 79;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 151, 0, 152);
        jPanel1.add(buttonOptionListarVagoes, gridBagConstraints);

        labelMenuEdicao.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        labelMenuEdicao.setForeground(new java.awt.Color(255, 255, 249));
        labelMenuEdicao.setText("Menu de Opções");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(64, 204, 0, 0);
        jPanel1.add(labelMenuEdicao, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOptionInserirLocomotivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOptionInserirLocomotivaActionPerformed
        JFrameInserirLocomotiva jfLoco = new JFrameInserirLocomotiva();
        jfLoco.infoCollector(gc,patio);
        jfLoco.setVisible(true);
    }//GEN-LAST:event_buttonOptionInserirLocomotivaActionPerformed

    private void buttonOptionRemoverCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOptionRemoverCarroActionPerformed
        JFrameRemoveUltimo jfUltimo = new JFrameRemoveUltimo();
        jfUltimo.infoCollector(gc,patio);
        jfUltimo.setVisible(true);
    }//GEN-LAST:event_buttonOptionRemoverCarroActionPerformed

    private void buttonOptionInserirVagaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOptionInserirVagaoActionPerformed
        JFrameInserirVagao jfVagao = new JFrameInserirVagao();
        jfVagao.infoCollector(gc,patio);
        jfVagao.setVisible(true);
    }//GEN-LAST:event_buttonOptionInserirVagaoActionPerformed

    private void buttonOptionListarLocomotivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOptionListarLocomotivasActionPerformed
        JFrameListarLocomotivas jfLoco = new JFrameListarLocomotivas();
        jfLoco .infoCollector(gc,patio);
        jfLoco .setVisible(true);
    }//GEN-LAST:event_buttonOptionListarLocomotivasActionPerformed

    private void buttonOptionListarVagoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOptionListarVagoesActionPerformed
        JFrameListarVagoes jfVagoes = new JFrameListarVagoes();
        jfVagoes .infoCollector(gc,patio);
        jfVagoes .setVisible(true);
    }//GEN-LAST:event_buttonOptionListarVagoesActionPerformed

    public void infoCollector(GaragemCarros gc, Patio patio){
        this.gc = gc;
        this.patio = patio;
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOptionInserirLocomotiva;
    private javax.swing.JButton buttonOptionInserirVagao;
    private javax.swing.JButton buttonOptionListarLocomotivas;
    private javax.swing.JButton buttonOptionListarVagoes;
    private javax.swing.JButton buttonOptionRemoverCarro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelMenuEdicao;
    // End of variables declaration//GEN-END:variables
}
