package rocket.tfpoo;
import javax.swing.JOptionPane;

/**
 *
 * @author yasmin
 */
public class JFrameInserirLocomotiva extends javax.swing.JFrame {
    private GaragemCarros gc;
    private Patio patio;
    private Leitor leitor;
    /**
     * Creates new form JFrameInserirLocomotiva
     */
    public JFrameInserirLocomotiva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        comboTrem = new javax.swing.JComboBox<>();
        comboLocomotiva = new javax.swing.JComboBox<>();
        buttonAdicionarLocomotiva = new javax.swing.JButton();
        labelLocomotiva = new javax.swing.JLabel();
        labelTrem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 215, 204));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        comboTrem.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 178;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(154, 6, 0, 135);
        jPanel1.add(comboTrem, gridBagConstraints);

        comboLocomotiva.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        comboLocomotiva.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 178;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 6, 0, 135);
        jPanel1.add(comboLocomotiva, gridBagConstraints);

        buttonAdicionarLocomotiva.setBackground(new java.awt.Color(255, 153, 153));
        buttonAdicionarLocomotiva.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        buttonAdicionarLocomotiva.setForeground(new java.awt.Color(255, 255, 249));
        buttonAdicionarLocomotiva.setText("Adicionar");
        buttonAdicionarLocomotiva.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonAdicionarLocomotiva.setDefaultCapable(false);
        buttonAdicionarLocomotiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarLocomotivaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 69;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 289, 168, 0);
        jPanel1.add(buttonAdicionarLocomotiva, gridBagConstraints);

        labelLocomotiva.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        labelLocomotiva.setForeground(new java.awt.Color(255, 255, 249));
        labelLocomotiva.setText("Escolha uma locomotiva:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 94, 0, 0);
        jPanel1.add(labelLocomotiva, gridBagConstraints);

        labelTrem.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        labelTrem.setForeground(new java.awt.Color(255, 255, 249));
        labelTrem.setText("Escolha um trem:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(152, 181, 0, 0);
        jPanel1.add(labelTrem, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAdicionarLocomotivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarLocomotivaActionPerformed
        if(comboLocomotiva.getSelectedItem() == null){
            JOptionPane.showMessageDialog(JFrameInserirLocomotiva.this, "Nenhuma locomotiva disponível.", "Erro", JOptionPane.ERROR_MESSAGE);
        }else{
            String selected = comboLocomotiva.getSelectedItem().toString();
            String id = selected.substring(12, selected.length());
            int idLocomotiva = Integer.parseInt(id);
            selected = comboTrem.getSelectedItem().toString();
            id = selected.substring(6, selected.length());
            int idTrem = Integer.parseInt(id);
            Locomotiva locoadd = (Locomotiva) gc.getCarro(idLocomotiva);
            Trem tremadd = patio.getTrem(idTrem);
            boolean engatado = tremadd.engataLocomotiva(locoadd,gc);
            if(engatado){
                JOptionPane.showMessageDialog(JFrameInserirLocomotiva.this, "Locomotiva inserida com sucesso!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
                leitor.reescreverComposicao();
            }
            int index = comboLocomotiva.getSelectedIndex();
            comboLocomotiva.removeItemAt(index);
        }
    }//GEN-LAST:event_buttonAdicionarLocomotivaActionPerformed
    public void infoCollector(GaragemCarros gc, Patio patio){
        this.gc = gc;
        this.patio = patio;
        leitor = new Leitor(gc, patio);
        for(Carro c:gc.garagemCarro){
            if(c instanceof Locomotiva){
                String item = "Locomotiva: "+c.id;
                comboLocomotiva.addItem(item);
            }
        }
        for(Trem t:patio.trens){
            if(t.getQuantVagoes() == 0){
                String item = "Trem: "+t.getId();
                comboTrem.addItem(item);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionarLocomotiva;
    private javax.swing.JComboBox<String> comboLocomotiva;
    private javax.swing.JComboBox<String> comboTrem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelLocomotiva;
    private javax.swing.JLabel labelTrem;
    // End of variables declaration//GEN-END:variables
}
